### ISSUE TITLE
usernames aren't case-idependent

### ISSUE THREAD

**Issue by dwaq** [cwbuecheler/closebrace-keystone#33]
I'm using Twitter as an example. These both lead to one user.
https://twitter.com/cwbuecheler
https://twitter.com/CWBuecheler

These are 2 different users (sorry for using your name as an example).
https://dev.closebrace.com/u/cwbuecheler
https://dev.closebrace.com/u/CWBuecheler

This seems like it could be an issue.

**Comment by cwbuecheler** [comment]
Good catch. This is a major issue.

**Comment by dwaq** [comment]
You can delete the profile I made to submit this bug: https://dev.closebrace.com/u/CWBuecheler Right now this link points to the new profile. Maybe you want to look into this more to determine why it's not redirecting to your actual profile?

**Comment by cwbuecheler** [comment]
I think this is fixed now. Reason it was still showing the old profile is because it was doing a case-independent search, getting back two profiles, but then only sending the data for the newer one on to the view for rendering.
