### ISSUE TITLE
Youtube icon on footer has display issue

### ISSUE THREAD

**Issue by dwaq** [cwbuecheler/closebrace-keystone#40]
The YouTube icon has an issue on a specific resolution/zoom level in Chrome. There appears to be a small line above the icon. My display was set up to 1280x1024 and the Chrome 56.0.2924.87 (64-bit) on Windows was set to 90% zoom. You may/may not be able to reproduce this so here's screenshots.
![bad](https://cloud.githubusercontent.com/assets/1299430/23480716/e69b3a2a-fe96-11e6-9526-28ba5423bc79.png)
![good](https://cloud.githubusercontent.com/assets/1299430/23480715/e696d818-fe96-11e6-932a-f71151863654.png)
By changing the offset, I was able to fix the issue.

**Comment by cwbuecheler** [comment]
Yeah, what's happening is there's no padding in the sprite, so depending on zoom level it's having some issues. Shouldn't be hard to fix -- just replace the sprite with a version that has a few px of transparency between the images.
