### ISSUE TITLE
Searching for nothing returns everything

### ISSUE THREAD

**Issue by dwaq** [cwbuecheler/closebrace-keystone#42]
Open the search bar and click "GO" without typing anything.
It displays: `Tags Matching ""` and then lists many (probably all available) tags and posts.
Other websites typically return nothing or don't try to search when the bar is blank.
Maybe this is the desired behavior, but I think the results will get unruly when there's tons of posts in the future.

**Comment by cwbuecheler** [comment]
Good catch. Definitely need to do a check for a blank string submission.
