### ISSUE TITLE
Prevent discovery of who has a CloseBrace account

### ISSUE THREAD

**Issue by jtbennett** [cwbuecheler/closebrace-keystone#56]
When I go to reset password and enter a fake address, I see the error message: "Sorry, that email doesn't exist in our database."  This allows people to discover who has or does not have an account.  

Suggestion: Display the same message after submitting the Forgot Password form, whether the account exists or not: "All set. If an account with your email address exists, we have emailed you a link to reset your password".

I'm happy to send a PR.

**Comment by cwbuecheler** [comment]
Agreed, this is a better solution. I'd be happy to have the PR, but if you don't have time, I'll get it in there before launch. :)

**Comment by cwbuecheler** [comment]
Closed in the develop branch, will roll out to staging/master today.
